version: "3.6"
volumes:
  dbdata:
networks:
  node-network:
    driver: bridge
services:
  nodejs:
    restart: unless-stopped # Set to 'always' for automatically restart
    build: 
      context: .
    user: "${UID}:${GID}"
    tty: true
    ports:
      - 80:3000
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      WAIT_HOSTS: mongodb:27017
      MONGODB_URL: ${MONGODB_URL}
    command:
      - bash
      - -c
      - "npm run test"
    networks:
      - node-network
    deploy:
      resources:
        limits:
          cpus: '${nodejs_cpus_limit}'
          memory: ${nodejs_memory_limit}
        reservations:
          cpus: '${nodejs_cpus_request}'
          memory: ${nodejs_memory_request}
  mongodb:
    image: mongo:4.2.1-bionic
    restart: unless-stopped # Set to 'always' for automatically restart
    user: "${UID}:${GID}"
    ports:
      - 27017:27017
    volumes:
      - ${db_source}:/data/db:rw
    networks:
      - node-network
    deploy:
      resources:
        limits:
          cpus: '${mongodb_cpus_limit}'
          memory: ${mongodb_memory_limit}
        reservations:
          cpus: '${mongodb_cpus_request}'
          memory: ${mongodb_memory_request}