{{- if .Values.ingress.enabled -}}
{{- $fullName := include "nodejs.fullname" . -}}

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}-http
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ .Values.ingress.host }}`)
      kind: Rule
      services:
      - name: {{ $fullName }}
        port: 80
      middlewares:
        - name: https-redirect

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}-https
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.ingress.host }}`)
      kind: Rule
      services:
      - name: {{ $fullName }}
        port: 80
  tls:
    certResolver: {{ .Values.ingress.certResolver }}

{{- end }}