apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "nodejs.fullname" . }}
  name: {{ include "nodejs.fullname" . }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: {{ include "nodejs.fullname" . }}
  sessionAffinity: None
  type: ClusterIP