helmDefaults:
  kubeContext: pintu-test
  timeout: 900

templates:
  default: &default
    chart: stable/{{`{{ .Release.Name }}`}}
    namespace: default
    # This prevents helmfile exiting when it encounters a missing file
    # Valid values are "Error", "Warn", "Info", "Debug". The default is "Error"
    # Use "Debug" to make missing files errors invisible at the default log level(--log-level=INFO)
    missingFileHandler: Warn
    values:
    - values/{{`{{ .Release.Name }}`}}/values.yaml
    secrets:
    - values/{{`{{ .Release.Name }}`}}/secrets.yaml

releases:
  - name: traefik
    <<: *default 
    chart: traefik/traefik
    version: ~10.19.5
    values:
      - values/traefik/values.yaml

  - name: traefik-nfs
    <<: *default 
    installed: true
    chart: stable/nfs-server-provisioner
    version: ~1.1.3
    values:
      - values/traefik-nfs/values.yaml
  
  - name: nodejs-pintu-test
    <<: *default
    installed: true
    chart: ../chart/nodejs
    values:
      - values/nodejs-pintu-test/values.yaml

  - name: nodejs-pintu-dev
    <<: *default
    installed: true
    chart: ../chart/nodejs
    values:
      - values/nodejs-pintu-dev/values.yaml
  
  - name: nodejs-pintu-prod
    <<: *default
    installed: true
    chart: ../chart/nodejs
    values:
      - values/nodejs-pintu-prod/values.yaml

  
repositories:
  - name: stable
    url: "https://charts.helm.sh/stable"
  - name: k8s-at-home
    url: "https://k8s-at-home.com/charts/"
  - name: incubator
    url: https://charts.helm.sh/incubator
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: traefik
    url: https://helm.traefik.io/traefik